### ISSUE TITLE
Shipprinter super topic!

### ISSUE THREAD

**Issue by zelrond** [StarLegacy/Issue-Tracker#182]
- No need for gold to money print. That means even if you dont want to, it will consume your money when printing (an option to only matprint is needed)
- Printing large structures isn't working like before, you can detect and blueprint a large shape that enters your loaded chunks, but when printing, since you must click on the printer and printing is now instantaneous, it doesn't print the unloaded chunks (your position is now on a corner, not the center) so the structure doesn't print. Two options, make printing not instantaneous like before, that way you can "run" and load the chunks or making the printing be able to print outside loaded chunks like before.
- Color materials, Materials with statuses (sponge wet or dry), they arent interchangable like before. I dunno if it's gonna stay like that or not, Gutin mentioned it possibly wouldn't
- stone_brick_slab[type=doubble] was before the one block we could transform into quartz, nether, sandstone, brick and smooth stone and obviously stone_brick double_stone_slab. Now that doesn't work it seems. Just so you know IF you wanted to keep it too.
- prices for all the new id's are missing, so concrete, stained_glasses, terracottas, they don't money print now.
- when printing, it always leaves ONE block of each kind in the chest, i dont know if its on purpose (and it could help as an interesting mechanic actually!!!) just so you know that it happens... i think this could stay (you will always need 1 more of each thing to print your stuff)

I think that's it!

**Comment by MicleBrick** [comment]
1. from now on open a separate issue per bug
2. now you can left click to money print, right click to material print only
3. that's intentional, you should only have blueprints in loaded chunks. split it up into smaller blueprints.
4. it will stay needing you to have the right material
5. @Gutin1 is going to fix the prices or get someone to do it soon, God willing
6. It's intentional that it leaves one to make it easy to use pipes.
