### ISSUE TITLE
Thruster DC glitch

### ISSUE THREAD

**Issue by silkbeast** [StarLegacy/Issue-Tracker#209]
When in a Starfighter with Afterburner thrusters, no matter the way they are pointed, when DCing, slots 3-9 go backwards and slot 1 makes it go forward.

**To Reproduce**
Build a starfighter with afterburners, do /dc and check each slot.

**Expected behavior**
When in a Starfighter with Afterburner thrusters, when DCing, slots 3-9 go forward, and slot 1 going backwards.

**System (please complete the following information):**
- OS: Windows
- CPU: 4x AMD FX(tm)-4300 Quad-Core Processor
- RAM: 8gb RAM
- Minecraft Version: Minecraft Java Edition 1.16.3

**Comment by hafarooki** [comment]
Most likely this is simply because you have more thrust in the reverse direction than the forward direction, hence the plugin considers your backwards the ship's forward. Rectify this issue. If the issue persists, open a new issue with screenshots of a minimal construct "ship" that reproduces the issue.
