### ISSUE TITLE
[BUG] Advancements are broken for players with the 8i advancement

### ISSUE THREAD

**Issue by kwazedilla** [StarLegacy/Issue-Tracker#236]
**Describe the bug**

Right clicking any multiblock sign does not detect the multiblock if one has the "mod" rank. Multiblocks that were detected before this bug still function normally. Normal players may still detect multiblocks normally.

**To Reproduce**

Make any multiblock and attempt to detect it, while having the "mod" rank.

**Expected behavior**

The multiblock should detect when right clicking the sign.

**Screenshots**

**System (please complete the following information):**

- OS: Windows
- RAM: 8gb RAM
- Minecraft Version: 1.16.3, Optifine HD U G3

**Additional context**

Does not work on TurqTheDemonKing and Kwazedilla. Works on both of our alts.

**Comment by saltypoe** [comment]
Hello, unfortunately this issue is not only affecting players with the mod ranking, I also am unable to detect multiblock signs at the moment. As of right now I have been unable to detect shields, hyperdrive, navigation computers, airlocks, docking tubes and gravity wells. The issue seemed to start on the day that mesh shields were implemented. I do have the purchased rank of Captain, don't know if maybe the issue involves players with purchased or staff ranks.

**Comment by hafarooki** [comment]
issue was that 8i shield advancement was not in all caps
